settings:
  title: '服务器状态'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有服务正常'
  notAllmonitorsOperational: '服务出现异常'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '异常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 异常记录' # xx incident(s) recorded

monitors:
  - id: main # unique identifier
    name: hazama.cc
    description: 'My Home' # default=empty
    url: 'https://hazama.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
